name: Node.js CI

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - feature/add-new-feature
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Fetch all branches
        run: git fetch --all

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Checkout feature branch
        run: git checkout feature/add-new-feature

      - name: Merge main into feature branch favoring feature branch changes
        run: git merge -s ours main

      - name: Checkout main branch
        run: git checkout main

      - name: Merge feature branch into main
        run: git merge --no-ff feature/add-new-feature -m "Auto-merge feature/add-new-feature"

      - name: Push changes
        run: git push
